enum UsersActionType {
    GET_USERS_INITIAL = 'GET_USERS_INITIAL',
    GET_USERS_SUCCESS = 'GET_USERS_SUCCESS',
    GET_USERS_ERROR = 'GET_USERS_ERROR',

    GET_USER = 'GET_USER',
    CLEAR_USER_DETAIL = 'CLEAR_USER_DETAIL',

    UPDATE_USER_INITIAL = 'UPDATE_USER_INITIAL',
    UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS',
    UPDATE_USER_ERROR = 'UPDATE_USER_ERROR',

    CREATE_USER_INITIAL = 'CREATE_USER_INITIAL',
    CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS',
    CREATE_USER_ERROR = 'CREATE_USER_ERROR',

    DELETE_USER_INITIAL = 'DELETE_USER_INITIAL',
    DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS',
    DELETE_USER_ERROR = 'DELETE_USER_ERROR'
}

export default UsersActionType
